leftnav:
- identifier: 97201615-57d4-4c5a-9098-a9446cb27d7c
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 64c0e042-1482-4cbc-bc20-e7952bc8f254
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 1f3f9f0f-79a4-4628-9334-9e10d34ae9bd
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 0f449cfe-c4fc-4a88-86ba-58c2cd920fdd
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 6dbb0523-b9d2-4df5-aaf1-e814f09fc2e0
  name: Short Writing Assignment 1
  pageRef: /pages/short-writing-assignment-1
  parent: 0f449cfe-c4fc-4a88-86ba-58c2cd920fdd
  weight: 10
- identifier: 807fc503-a058-42df-98f4-0ba26f167aee
  name: Short Writing Assignment 2
  pageRef: /pages/short-writing-assignment-2
  parent: 0f449cfe-c4fc-4a88-86ba-58c2cd920fdd
  weight: 20
- identifier: bf040e6f-1831-4a13-b385-b82be57ae666
  name: Short Writing Assignment 3
  pageRef: /pages/short-writing-assignment-3
  parent: 0f449cfe-c4fc-4a88-86ba-58c2cd920fdd
  weight: 30
- identifier: 51f95672-fa90-439f-87a0-54e5ea8c15b8
  name: Final Essay
  pageRef: /pages/final-essay
  parent: 0f449cfe-c4fc-4a88-86ba-58c2cd920fdd
  weight: 40
